### ISSUE TITLE
GIMP + ComfyUI

### ISSUE THREAD

**Issue by devingfx** [Charlweed/gimp_sd_a1111_github#1]
Hi !

Where is downloadable the GIMP + ComfyUI plugin you speak about in this README ?
Have you started it yet ?
Is it meant to be libre and accessible ?

Thx btw :)

**Comment by Charlweed** [comment]
You can look at https://github.com/Charlweed/gimp_comfyui. It also requires GIMP 2.99. The details are in the README.
